services:
  php:
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - .:/app
      - .env.local:/app/.env.local:ro
      - .env.dev:/app/.env.dev:ro

###> doctrine/doctrine-bundle ###
  database:
###< doctrine/doctrine-bundle ###

  worker:
    volumes:
      - .:/app
      - .env.local:/app/.env.local:ro

  scheduler:
    volumes:
      - .:/app
      - .env.local:/app/.env.local:ro
