<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260712100513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE analysis_results (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(50) NOT NULL, model TEXT DEFAULT NULL, classification JSON NOT NULL, tokens_used INT DEFAULT NULL, cost DOUBLE PRECISION DEFAULT NULL, duration_ms INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E57282123D5814AC ON analysis_results (commit_id)');
        $this->addSql('CREATE TABLE commits (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sha VARCHAR(40) NOT NULL, author_email VARCHAR(255) NOT NULL, author_name VARCHAR(255) NOT NULL, message TEXT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, additions INT NOT NULL, deletions INT NOT NULL, files_changed INT NOT NULL, is_merge_commit BOOLEAN NOT NULL, diff_stats JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, repository_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B327C47050C9D4F7 ON commits (repository_id)');
        $this->addSql('CREATE TABLE github_accounts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, github_username VARCHAR(100) NOT NULL, encrypted_token TEXT NOT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2012D00DA76ED395 ON github_accounts (user_id)');
        $this->addSql('CREATE TABLE issues (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, github_id INT NOT NULL, title VARCHAR(500) NOT NULL, body TEXT DEFAULT NULL, state VARCHAR(20) NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, labels JSON NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, repository_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DA7D7F8350C9D4F7 ON issues (repository_id)');
        $this->addSql('CREATE TABLE pull_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, github_id INT NOT NULL, title VARCHAR(500) NOT NULL, body TEXT DEFAULT NULL, state VARCHAR(20) NOT NULL, merged BOOLEAN NOT NULL, additions INT NOT NULL, deletions INT NOT NULL, changed_files INT NOT NULL, merged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, repository_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B30AB7C50C9D4F7 ON pull_requests (repository_id)');
        $this->addSql('CREATE TABLE repositories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, github_id INT NOT NULL, full_name VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, language VARCHAR(50) DEFAULT NULL, stars INT NOT NULL, forks INT NOT NULL, is_fork BOOLEAN NOT NULL, is_private BOOLEAN NOT NULL, metadata JSON NOT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE github_repo_github_account (github_repo_id INT NOT NULL, github_account_id INT NOT NULL, PRIMARY KEY (github_repo_id, github_account_id))');
        $this->addSql('CREATE INDEX IDX_5C70D30CB23C03A9 ON github_repo_github_account (github_repo_id)');
        $this->addSql('CREATE INDEX IDX_5C70D30CBD13545F ON github_repo_github_account (github_account_id)');
        $this->addSql('CREATE TABLE github_repo_technology (github_repo_id INT NOT NULL, technology_id INT NOT NULL, PRIMARY KEY (github_repo_id, technology_id))');
        $this->addSql('CREATE INDEX IDX_C3E360D8B23C03A9 ON github_repo_technology (github_repo_id)');
        $this->addSql('CREATE INDEX IDX_C3E360D84235D463 ON github_repo_technology (technology_id)');
        $this->addSql('CREATE TABLE sync_jobs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, items_processed INT NOT NULL, error_log JSON NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, github_account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FA45C18ABD13545F ON sync_jobs (github_account_id)');
        $this->addSql('CREATE TABLE technologies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, category VARCHAR(50) NOT NULL, version VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, settings JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE analysis_results ADD CONSTRAINT FK_E57282123D5814AC FOREIGN KEY (commit_id) REFERENCES commits (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commits ADD CONSTRAINT FK_B327C47050C9D4F7 FOREIGN KEY (repository_id) REFERENCES repositories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE github_accounts ADD CONSTRAINT FK_2012D00DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE issues ADD CONSTRAINT FK_DA7D7F8350C9D4F7 FOREIGN KEY (repository_id) REFERENCES repositories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pull_requests ADD CONSTRAINT FK_2B30AB7C50C9D4F7 FOREIGN KEY (repository_id) REFERENCES repositories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE github_repo_github_account ADD CONSTRAINT FK_5C70D30CB23C03A9 FOREIGN KEY (github_repo_id) REFERENCES repositories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE github_repo_github_account ADD CONSTRAINT FK_5C70D30CBD13545F FOREIGN KEY (github_account_id) REFERENCES github_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE github_repo_technology ADD CONSTRAINT FK_C3E360D8B23C03A9 FOREIGN KEY (github_repo_id) REFERENCES repositories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE github_repo_technology ADD CONSTRAINT FK_C3E360D84235D463 FOREIGN KEY (technology_id) REFERENCES technologies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sync_jobs ADD CONSTRAINT FK_FA45C18ABD13545F FOREIGN KEY (github_account_id) REFERENCES github_accounts (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE analysis_results DROP CONSTRAINT FK_E57282123D5814AC');
        $this->addSql('ALTER TABLE commits DROP CONSTRAINT FK_B327C47050C9D4F7');
        $this->addSql('ALTER TABLE github_accounts DROP CONSTRAINT FK_2012D00DA76ED395');
        $this->addSql('ALTER TABLE issues DROP CONSTRAINT FK_DA7D7F8350C9D4F7');
        $this->addSql('ALTER TABLE pull_requests DROP CONSTRAINT FK_2B30AB7C50C9D4F7');
        $this->addSql('ALTER TABLE github_repo_github_account DROP CONSTRAINT FK_5C70D30CB23C03A9');
        $this->addSql('ALTER TABLE github_repo_github_account DROP CONSTRAINT FK_5C70D30CBD13545F');
        $this->addSql('ALTER TABLE github_repo_technology DROP CONSTRAINT FK_C3E360D8B23C03A9');
        $this->addSql('ALTER TABLE github_repo_technology DROP CONSTRAINT FK_C3E360D84235D463');
        $this->addSql('ALTER TABLE sync_jobs DROP CONSTRAINT FK_FA45C18ABD13545F');
        $this->addSql('DROP TABLE analysis_results');
        $this->addSql('DROP TABLE commits');
        $this->addSql('DROP TABLE github_accounts');
        $this->addSql('DROP TABLE issues');
        $this->addSql('DROP TABLE pull_requests');
        $this->addSql('DROP TABLE repositories');
        $this->addSql('DROP TABLE github_repo_github_account');
        $this->addSql('DROP TABLE github_repo_technology');
        $this->addSql('DROP TABLE sync_jobs');
        $this->addSql('DROP TABLE technologies');
        $this->addSql('DROP TABLE users');
    }
}
